version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # É uma boa prática carregar o .env diretamente com a API,
      # mas para Docker Compose, definir aqui é mais direto
      DATABASE_URL: postgresql://user:password@db:5432/iot_db
      SECRET_KEY: "sua_chave_secreta_super_segura_aqui_para_jwt_nao_esqueça_de_mudar_em_producao_mesmo"
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      - db
    volumes:
      - .:/app # Mantém este volume para desenvolvimento, permitindo --reload
    # ATENÇÃO: Mudança AQUI
    command: ["bash", "-c", "uvicorn app.main:create_app --host 0.0.0.0 --port 8000 --reload --factory"]


volumes:
  db_data: